#!/bin/sh 

set -e

#echo "running bootstrap"
#echo "================="
#echo "env: "
#env
#echo "================="
#echo "pwd: $(pwd)"
#echo "$(ls .)"
#echo "================="

export BABASHKA_PODS_DIR=${LAMBDA_TASK_ROOT}/pods

./bb -jar lambda.jar -m bblf.runtime ${_HANDLER}

